version: '3.5'

volumes:
  wordpress:
  mariadb:
    # name: wordpress_ss
    # driver: local
    # driver_opts:
    #   device: //Users/yoelhaim/42/inception/srcs/requirements/wordpress/site
    #   o: bind
    #   type: none
    #   mariadb:
    #     name: mariadb
    #     driver: local
    #     driver_opts:
    #       device: /Users/pro/Desktop/inception/srcs/requirements/mariadb
    #       o: bind
    #       type: non
networks:
  inception:
    name: inception
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/.
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/.
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  ngnix:
    image: nginx
    container_name: ngnix_container
    build: ./requirements/nginx/.
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
  myweb:
    container_name: myweb_container
    build: ./requirements/bonus/website/.
    ports:
      - 3000:3000
    env_file:
      - .env
  adminer:
    image: adminer
    container_name: adminer_container
    build: ./requirements/bonus/adminer/.
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
