version: '3.5'

volumes:
  wordpress:
    name: v_wp
    driver: local
    driver_opts:
      device: /Users/yoelhaim/Desktop/docker/services
      o: bind
      type: none
  mariadb:
    name: v_mariadb
    driver: local
    driver_opts:
      device: /Users/yoelhaim/Desktop/docker/mariadb
      o: bind
      type: none
networks:
  inception:
    name: inception
    driver: bridge
services:
  mariadb:
    image: mariadb:42
    container_name: mariadb
    build: ./requirements/mariadb/.
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    image: wordpress:42
    container_name: wordpress
    build: ./requirements/wordpress/.
    ports:
      - 9000:9000
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always
  ngnix:
    image: nginx:42
    container_name: ngnix_container
    build: ./requirements/nginx/.
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env
  myweb:
    image: portfolio:42
    container_name: myweb_container
    build: ./requirements/bonus/website/.
    ports:
      - 3000:3000
    env_file:
      - .env
  adminer:
    image: adminer:42
    container_name: adminer
    build: ./requirements/bonus/adminer/.
    ports:
      - "500:500"
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
